### ISSUE TITLE
Rename to awesome.

### ISSUE THREAD

**Issue by JorgeBucaran** [hyperapp/awesome-hyperapp#16]
Since this repo is inside the `hyperapp` org already, can we rename it to just **awesome**?

/cc @tobiasbueschel @lukejacksonn @zaceno @selfup

**Comment by lukejacksonn** [comment]
Is it not convention that awesome repos are named like this?

**Comment by JorgeBucaran** [comment]
@lukejacksonn Possibly, but I am not sure, maybe there are exceptions? Like in this case.

**Comment by lukejacksonn** [comment]
I do think `hyperapp/awesome` looks better.. but https://github.com/sindresorhus/awesome/blob/master/create-list.md pretty clearly states:

> Your awesome list should be named `awesome-list-name`

I know technically we can name it however we want but I know @sindresorhus has worked pretty hard to maintain consistency and quality amongst all _awesome_ repos. I appreciate this effort, and think the underlying level of consistency is beautiful; therefore I would adhere to convention rather than break it based on surface level aesthetics.

What is it they say... without rules there is only chaos 😅 

2¢

**Comment by sindresorhus** [comment]
I personally prefer the repetition as the name is more descriptive when cloned. If someone clones `hyperapp/awesome` it will end up as `awesome` on their system, instead of `awesome-hyperapp`. But you're free to go with just `awesome` if you prefer.

**Comment by JorgeBucaran** [comment]
> @sindresorhus But you're free to go with just awesome if you prefer.

We have a filed a PR to add this list to sindresorhus/awesome, and I'd really appreciate if we can merge it even if we end up changing the name to just `awesome`. 


> If someone clones hyperapp/awesome it will end up as awesome on their system...

This is very a good point. 🤔
